[2025-06-03T17:24:30.480+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-03T17:24:30.496+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_extraction_pipeline.fetch_all_round_details manual__2025-06-03T17:24:20+00:00 [queued]>
[2025-06-03T17:24:30.499+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_extraction_pipeline.fetch_all_round_details manual__2025-06-03T17:24:20+00:00 [queued]>
[2025-06-03T17:24:30.500+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-03T17:24:30.505+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_all_round_details> on 2025-06-03 17:24:20+00:00
[2025-06-03T17:24:30.508+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_extraction_pipeline', 'fetch_all_round_details', 'manual__2025-06-03T17:24:20+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/f1_pipeline.py', '--cfg-path', '/tmp/tmphi9dod8o']
[2025-06-03T17:24:30.509+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask fetch_all_round_details
[2025-06-03T17:24:30.509+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=217) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-03T17:24:30.510+0000] {standard_task_runner.py:63} INFO - Started process 218 to run task
[2025-06-03T17:24:30.532+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_extraction_pipeline.fetch_all_round_details manual__2025-06-03T17:24:20+00:00 [running]> on host 660eef8a4153
[2025-06-03T17:24:30.656+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_extraction_pipeline' AIRFLOW_CTX_TASK_ID='fetch_all_round_details' AIRFLOW_CTX_EXECUTION_DATE='2025-06-03T17:24:20+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-03T17:24:20+00:00'
[2025-06-03T17:24:30.656+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-03T17:24:30.661+0000] {logging_mixin.py:188} INFO - Extraction des résultats pour l'année 2024, rounds : None
[2025-06-03T17:24:30.662+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-03T17:24:30.662+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/f1_pipeline.py", line 18, in _fetch_all_rounds_callable
    fetch_race_results(year=year, round_num=int(r_num))
                                            ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'N'
[2025-06-03T17:24:30.667+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=f1_data_extraction_pipeline, task_id=fetch_all_round_details, run_id=manual__2025-06-03T17:24:20+00:00, execution_date=20250603T172420, start_date=20250603T172430, end_date=20250603T172430
[2025-06-03T17:24:30.673+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task fetch_all_round_details (invalid literal for int() with base 10: 'N'; 218)
[2025-06-03T17:24:30.700+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-03T17:24:30.713+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-03T17:24:30.714+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
