[2025-06-03T17:32:48.685+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-03T17:32:48.700+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_extraction_pipeline.fetch_all_round_details manual__2025-06-03T17:32:43+00:00 [queued]>
[2025-06-03T17:32:48.703+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_extraction_pipeline.fetch_all_round_details manual__2025-06-03T17:32:43+00:00 [queued]>
[2025-06-03T17:32:48.704+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-03T17:32:48.708+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_all_round_details> on 2025-06-03 17:32:43+00:00
[2025-06-03T17:32:48.712+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=554) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-03T17:32:48.712+0000] {standard_task_runner.py:63} INFO - Started process 555 to run task
[2025-06-03T17:32:48.711+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_extraction_pipeline', 'fetch_all_round_details', 'manual__2025-06-03T17:32:43+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/f1_pipeline.py', '--cfg-path', '/tmp/tmpes3wv_g8']
[2025-06-03T17:32:48.713+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask fetch_all_round_details
[2025-06-03T17:32:48.735+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_extraction_pipeline.fetch_all_round_details manual__2025-06-03T17:32:43+00:00 [running]> on host 660eef8a4153
[2025-06-03T17:32:48.855+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_extraction_pipeline' AIRFLOW_CTX_TASK_ID='fetch_all_round_details' AIRFLOW_CTX_EXECUTION_DATE='2025-06-03T17:32:43+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-03T17:32:43+00:00'
[2025-06-03T17:32:48.856+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-03T17:32:48.860+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-03T17:32:48.860+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _fetch_all_rounds_callable() missing 1 required positional argument: 'rounds_list_str'
[2025-06-03T17:32:48.864+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=f1_data_extraction_pipeline, task_id=fetch_all_round_details, run_id=manual__2025-06-03T17:32:43+00:00, execution_date=20250603T173243, start_date=20250603T173248, end_date=20250603T173248
[2025-06-03T17:32:48.867+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 36 for task fetch_all_round_details (_fetch_all_rounds_callable() missing 1 required positional argument: 'rounds_list_str'; 555)
[2025-06-03T17:32:48.896+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-03T17:32:48.907+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-03T17:32:48.908+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
