[2025-06-03T18:48:27.993+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-03T18:48:28.010+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_extraction_pipeline.load_data_to_postgres manual__2025-06-03T18:47:49+00:00 [queued]>
[2025-06-03T18:48:28.014+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_extraction_pipeline.load_data_to_postgres manual__2025-06-03T18:47:49+00:00 [queued]>
[2025-06-03T18:48:28.014+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-03T18:48:28.021+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_to_postgres> on 2025-06-03 18:47:49+00:00
[2025-06-03T18:48:28.026+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_extraction_pipeline', 'load_data_to_postgres', 'manual__2025-06-03T18:47:49+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/f1_pipeline.py', '--cfg-path', '/tmp/tmpuao9uhgg']
[2025-06-03T18:48:28.032+0000] {standard_task_runner.py:91} INFO - Job 50: Subtask load_data_to_postgres
[2025-06-03T18:48:28.133+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=211) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-03T18:48:28.135+0000] {standard_task_runner.py:63} INFO - Started process 212 to run task
[2025-06-03T18:48:28.156+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_extraction_pipeline.load_data_to_postgres manual__2025-06-03T18:47:49+00:00 [running]> on host 272d0a595586
[2025-06-03T18:48:28.197+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_extraction_pipeline' AIRFLOW_CTX_TASK_ID='load_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-06-03T18:47:49+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-03T18:47:49+00:00'
[2025-06-03T18:48:28.197+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-03T18:48:28.202+0000] {logging_mixin.py:188} INFO - Début du chargement en base de données pour l'année 2024.
[2025-06-03T18:48:28.202+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-03T18:48:28.202+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/etl_scripts/load_to_postgres.py", line 86, in load_all_processed_data_to_postgres
    if not _load_single_csv_to_db(csv_file_path, item["table"], F1_POSTGRES_CONN_ID,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _load_single_csv_to_db() got an unexpected keyword argument 'year_to_clear'
[2025-06-03T18:48:28.208+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=f1_data_extraction_pipeline, task_id=load_data_to_postgres, run_id=manual__2025-06-03T18:47:49+00:00, execution_date=20250603T184749, start_date=20250603T184828, end_date=20250603T184828
[2025-06-03T18:48:28.213+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 50 for task load_data_to_postgres (_load_single_csv_to_db() got an unexpected keyword argument 'year_to_clear'; 212)
[2025-06-03T18:48:28.242+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-03T18:48:28.249+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-03T18:48:28.250+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
