[2025-06-03T17:29:13.868+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-03T17:29:13.881+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_extraction_pipeline.fetch_all_round_details manual__2025-06-03T17:29:08+00:00 [queued]>
[2025-06-03T17:29:13.884+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_extraction_pipeline.fetch_all_round_details manual__2025-06-03T17:29:08+00:00 [queued]>
[2025-06-03T17:29:13.885+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-03T17:29:13.889+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_all_round_details> on 2025-06-03 17:29:08+00:00
[2025-06-03T17:29:13.892+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_extraction_pipeline', 'fetch_all_round_details', 'manual__2025-06-03T17:29:08+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/f1_pipeline.py', '--cfg-path', '/tmp/tmplo3urmi0']
[2025-06-03T17:29:13.893+0000] {standard_task_runner.py:91} INFO - Job 33: Subtask fetch_all_round_details
[2025-06-03T17:29:13.893+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=412) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-03T17:29:13.894+0000] {standard_task_runner.py:63} INFO - Started process 413 to run task
[2025-06-03T17:29:13.914+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_extraction_pipeline.fetch_all_round_details manual__2025-06-03T17:29:08+00:00 [running]> on host 660eef8a4153
[2025-06-03T17:29:14.027+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_extraction_pipeline' AIRFLOW_CTX_TASK_ID='fetch_all_round_details' AIRFLOW_CTX_EXECUTION_DATE='2025-06-03T17:29:08+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-03T17:29:08+00:00'
[2025-06-03T17:29:14.027+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-03T17:29:14.031+0000] {logging_mixin.py:188} INFO - Extraction des résultats pour l'année 2024, rounds : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
[2025-06-03T17:29:14.031+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-03T17:29:14.032+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/f1_pipeline.py", line 17, in _fetch_all_rounds_callable
    for r_num in [int(i) for i in rounds_list]:
                  ^^^^^^
ValueError: invalid literal for int() with base 10: '['
[2025-06-03T17:29:14.036+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=f1_data_extraction_pipeline, task_id=fetch_all_round_details, run_id=manual__2025-06-03T17:29:08+00:00, execution_date=20250603T172908, start_date=20250603T172913, end_date=20250603T172914
[2025-06-03T17:29:14.039+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 33 for task fetch_all_round_details (invalid literal for int() with base 10: '['; 413)
[2025-06-03T17:29:14.077+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-03T17:29:14.088+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-03T17:29:14.090+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
